source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'
#inhibit_all_warnings!

def common
	pod 'WeexSDK'
	pod 'WeexPluginLoader'
	pod 'GTSDK', '2.0.0.0-noidfa'
end

target 'GetuiPush' do
    common
end


